### ISSUE TITLE
Scrollbars?

### ISSUE THREAD

**Issue by TauerOne** [rohit04saluja/brackets-zen-dark#1] opened 2017-01-26 20:40 UTC
Why do the scrollbars in the editor window disappear when using this theme?  Was that by design?

**Comment by rohit04saluja** [comment] 2017-01-26 23:28
Yes it was by design. You prefer it with the scrollbars?

**Comment by TauerOne** [comment] 2017-01-27 01:26
Yes.  I like your choices in this theme but I do like to have a scrollbar.
I see that I can hack your theme and allow the scrollbar to display very
easily.

Thanks.

**Comment by rohit04saluja** [comment] 2017-01-31 05:43
I am closing this issue. As it was design intended. Please do share the details of how you are hacking it to make it show the scrollbar, so anyone else with the same issue and use the hack.

Thanks.

**Closed as completed by rohit04saluja** 2017-01-31 05:43 UTC

**Comment by TauerOne** [comment] 2017-01-31 15:46
To make the scroll-bars visible again, comment out or remove lines 95-98 in the theme.less file. Those lines read:

`.CodeMirror-vscrollbar,`
`.CodeMirror-hscrollbar {`
`    display: none !important;`
`}`

Best Regards.
